# Generated by Django 4.0.1 on 2022-01-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_text_id', models.TextField()),
                ('child_text_id', models.TextField()),
                ('input_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.inputtext')),
            ],
        ),
    ]
