# Generated by Django 4.0.1 on 2022-01-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reletion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reletion',
            new_name='Relation',
        ),
    ]
