# Generated by Django 4.0.2 on 2022-03-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_synapse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='input_text',
        ),
        migrations.RemoveField(
            model_name='synapse',
            name='input_text',
        ),
        migrations.AddField(
            model_name='synapse',
            name='neuron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neuron'),
        ),
        migrations.DeleteModel(
            name='InputText',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
