# Generated by Django 4.0.2 on 2022-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_blog_remove_relation_input_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='status',
            field=models.IntegerField(choices=[(1, '未完了'), (2, '作業中'), (3, '完了')], default=1),
        ),
    ]
