# Generated by Django 4.0.1 on 2022-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='indent',
            field=models.IntegerField(default=0),
        ),
    ]
